---
sidebar: sidebar 
permalink: reference-azure-backup-tiers.html 
keywords: microsoft azure, azure, cool, access tier, archive 
summary: Cloud Backup 支持一个 Azure 归档访问层以及大多数地区。 
---
= Azure 归档层和还原检索时间
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup 支持一个 Azure 归档访问层以及大多数地区。



== 支持 Cloud Backup 的 Azure Blob 访问层

首次创建备份文件时，这些备份文件将存储在 _cool_ 访问层中。此层经过优化，可用于存储不常访问的数据；但在需要时，可以立即访问。

如果源集群运行的是 ONTAP 9.10.1 或更高版本，您可以选择在一定天数（通常超过 30 天）后将备份从 _cool_ 分层到 _Azure Archive_ 存储，以便进一步优化成本。此层中的数据无法在需要时立即访问，因此需要较高的检索成本，因此您需要考虑从这些归档备份文件还原数据的频率。请参见下一节 <<Restoring data from archival storage,从归档存储还原数据>>。

请注意，使用此类型的生命周期规则配置 Cloud Backup 时，在 Azure 帐户中设置容器时，不能配置任何生命周期规则。

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["了解 Azure Blob 访问层"^]。



== 从归档存储还原数据

虽然将旧备份文件存储在归档存储中的成本要比冷存储低得多，但从 Azure 归档中的备份文件访问数据以执行还原操作将需要较长的时间，并且成本也会更高。

从 Azure Archive 还原数据的成本是多少？:: 从 Azure Archive 检索数据时，您可以选择两个还原优先级：
+
--
* * 高 * ：检索速度最快，成本更高
* * 标准 * ：检索速度较慢，成本较低


每种方法的每 GB 检索费用和每次请求费用不同。有关按 Azure 地区列出的 Azure Archive 详细定价，请访问 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Azure 定价页面"]。

--
还原在 Azure Archive 中归档的数据需要多长时间？:: 还原时间由两部分组成：
+
--
* * 检索时间 * ：从 Azure Archive 检索已归档备份文件并将其置于冷存储中的时间。这有时称为 " 再融合 " 时间。根据您选择的还原优先级，检索时间会有所不同：
+
** * 高 * ： < 1 小时
** * 标准 * ： < 15 小时


* * 还原时间 * ：从冷存储中的备份文件还原数据的时间。这一时间与直接从冷存储执行的典型还原操作并无不同，因为此时不使用归档层。


有关 Azure 归档检索选项的详细信息，请参见 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/#faq["此 Azure 常见问题解答"]。

--

