---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: 您可以将 Oracle 数据库从云还原到内部 SnapCenter 服务器。 
---
= 还原 Oracle 数据库
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您只能将 Oracle 数据库还原到同一 SnapCenter 服务器主机，同一 SVM 或同一数据库主机。对于 RAC 数据库，数据将还原到创建备份的内部节点。

仅支持具有控制文件还原的完整数据库。如果归档日志不在 AFS 中，则应指定包含恢复所需归档日志的位置。

* 步骤 *

. 在 Cloud Manager UI 中，单击 * 备份和还原 * > * 应用程序 * 。
. 在 * 筛选依据 * 字段中，选择筛选器 * 类型 * ，然后从下拉列表中选择 * Oracle * 。
. 单击与要还原的数据库对应的 * 查看详细信息 * ，然后单击 * 还原 * 。
. 在还原类型页面上，执行以下操作：
+
.. 如果要还原控制文件以及完整数据库，请选择 * 控制文件 * 。
.. 选择 * 如果需要还原和恢复更改数据库状态 * ，将数据库的状态更改为执行还原和恢复操作所需的状态。
+
数据库从高到低的各种状态包括打开，挂载，启动和关闭。如果数据库处于较高状态，但要执行还原操作，必须将此状态更改为较低状态，则必须选中此复选框。如果数据库处于较低的状态，但要执行还原操作，必须将其更改为较高的状态，则即使未选中此复选框，数据库状态也会自动更改。

+
如果数据库处于打开状态，并且要还原，数据库需要处于挂载状态，则只有选中此复选框后，数据库状态才会更改。



. 在恢复范围页面上，执行以下操作：
+
.. 指定恢复范围。
+
|===
| 如果您 ... | 执行此操作 ... 


 a| 
希望恢复到上一个事务
 a| 
选择 * 所有日志 * 。



 a| 
希望恢复到特定的系统更改编号（ SCN ）
 a| 
选择 * 直到 SCN （系统更改编号） * 。



 a| 
希望恢复到特定数据和时间
 a| 
选择 * 日期和时间 * 。

必须指定数据库主机时区的日期和时间。



 a| 
不希望恢复
 a| 
选择 * 无恢复 * 。



 a| 
希望指定任何外部归档日志位置
 a| 
如果归档日志不在 AFS 中，则应指定包含恢复所需归档日志的位置。

|===
.. 如果要在恢复后打开数据库，请选中此复选框。
+
在 RAC 设置中，恢复后仅打开用于恢复的 RAC 实例。



. 查看详细信息并单击 * 还原 * 。

