---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: 您可以将 SQL Server 数据库从云还原到内部 SnapCenter Server 。 
---
= 还原 SQL Server 数据库
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将 SQL Server 数据库还原到同一主机或备用主机。不支持恢复日志备份和重新选择可用性组。

* 步骤 *

. 在 Cloud Manager UI 中，单击 * 备份和还原 * > * 应用程序 * 。
. 在 * 筛选依据 * 字段中，选择筛选器 * 类型 * ，然后从下拉列表中选择 * SQL * 。
. 单击 * 查看详细信息 * 以查看所有可用备份。
. 选择备份并单击 * 还原 * 。
. 选择要还原数据库文件的位置。
+
|===
| 选项 | Description 


 a| 
将数据库还原到创建备份的同一主机
 a| 
如果要将数据库还原到执行备份的同一 SQL 服务器，请选择此选项。



 a| 
将数据库还原到备用主机
 a| 
如果要将数据库还原到执行备份的同一主机或不同主机中的其他 SQL 服务器，请选择此选项。

选择主机名，提供数据库名称（可选），选择实例并指定还原路径。


NOTE: 备用路径中提供的文件扩展名必须与原始数据库文件的文件扩展名相同。

如果 " 还原范围 " 页面中未显示 * 将数据库还原到备用主机 * 选项，请清除浏览器缓存。

|===
. 在 * 还原前选项 * 页面上，选择以下选项之一：
+
** 选择 * 在还原期间覆盖同名数据库 * 以还原同名数据库。
** 选择 * 保留 SQL 数据库复制设置 * 以还原数据库并保留现有复制设置。


. 在 * 还原后选项 * 页面上，要指定用于还原其他事务日志的数据库状态，请选择以下选项之一：
+
** 如果要立即还原所有必要的备份，请选择 * 可操作，但不可用 * 。
+
这是默认行为，通过回滚未提交的事务使数据库做好使用准备。在创建备份之前，您无法还原其他事务日志。

** 选择 * 不可操作，但可用 * 可使数据库不可操作，而不回滚未提交的事务。
+
可以还原其他事务日志。在恢复数据库之前，您无法使用它。

** 选择 * 只读模式和可用 * 可使数据库保持只读模式。
+
此选项将撤消未提交的事务，但会将撤消的操作保存在备用文件中，以便可以还原恢复效果。

+
如果启用了撤消目录选项，则会还原更多事务日志。如果事务日志的还原操作失败，则可以回滚所做的更改。SQL Server 文档包含详细信息。



. 查看详细信息并单击 * 还原 * 。

